spring:
  config:
    activate:
      on-profile: default
dbname: dbname-default
test:
  value: Hello-default
---
spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'

aws:
  paramstore:
    enabled: true
    prefix: /project01
    profile-separator: _
    name: myapp

test:
  value: Hello-dev
